# Generated by Django 3.2.7 on 2021-09-16 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.CharField(max_length=50, null=True)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('inicia', models.TimeField()),
                ('termina', models.TimeField()),
                ('dia', models.DateField()),
            ],
            options={
                'verbose_name': 'Gym',
                'verbose_name_plural': 'Gyms',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Superior', 'Superior'), ('Superior Ejecutiva', 'Superior Ejecutiva'), ('Royal 2 Cama', 'Royal 2 Cama'), ('Royal 1 Cama', 'Royal 1 Cama'), ('HoneyMoon Suite', 'HoneyMoon Suite'), ('Caribe Suite', 'Caribe Suite')], max_length=200, null=True)),
                ('distinciones', models.CharField(choices=[('1 Cama', '1 Cama'), ('2 Cama', '2 Cama'), ('2 Cama + silla', '1 Cama + silita'), ('2 Cama + escritorio', '1 Cama + escritorio'), ('Balcon', 'Balcon'), ('Suite con Jacuzzi', 'Suite con Jacuzzi'), ('Suite', 'Suite')], max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Ocupado', 'Ocupado'), ('Sucia', 'Sucia'), ('Mantimiento', 'Mantenimiento'), ('Bloqueada', 'Bloqueada'), ('Libre', 'Libre')], max_length=200, null=True)),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.floor')),
            ],
        ),
    ]
