# Generated by Django 3.2.7 on 2021-09-18 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='inicia',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='termina',
        ),
        migrations.AddField(
            model_name='gym',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gym',
            name='dia',
            field=models.DateTimeField(),
        ),
    ]
