# Generated by Django 3.2.7 on 2021-09-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_auto_20210918_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
