# Generated by Django 3.2.7 on 2021-09-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0004_auto_20210918_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='end',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='start',
        ),
        migrations.AddField(
            model_name='gym',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
